### PR TITLE
Main module builds and tests pass for `boost.chrono`

### PR DESCRIPTION
**Pull request by andrewkatson**
The only tests omitted return failure on purpose. I looked into how to fix this and you have to create a nasty custom build rule which I thought was out of scope of this change.

### CODE REVIEW

**Comment by zaucy** [comment]
> The only tests omitted return failure on purpose

That's fine. the bazel tests don't have to be perfect. Just enough to make sure the bazel module works.

I added a github action to run the tests. When we're green then I'll get it merged in!

**Comment by andrewkatson** [comment]
Okay Ill keep modifying until it gets green!

**Comment by andrewkatson** [comment]
Added a missing `@`. I hope it works after this *fingers crossed*

**Review by zaucy — APPROVED** [review]

**Comment by zaucy** [comment]
Looks like the boost autolinker is enabled causing the windows ci to fail. Generally I've been disabling this since an autolinker doesn't make much sense with bazel built projects.

**Comment by zaucy** [comment]
i disabled autolink to get it through! Thanks so much :)

**Comment by andrewkatson** [comment]
Thank you!

**Pull request merged**
